openapi: 3.0.1
info:
  title: SFTP
  description: API Definition of SFTP
  version: 1.0.0
servers:
- url: http://localhost:8290/parse
paths:
  /:
    get:
      responses:
        default:
          description: Default response
